# Generated by Django 3.1.7 on 2022-08-09 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_sneaker_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sneaker_size',
        ),
    ]
