# Generated by Django 3.1.7 on 2022-08-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_sneaker_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sneaker_size',
            field=models.IntegerField(default=0),
        ),
    ]
