# Generated by Django 3.1.7 on 2022-08-10 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20220809_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sneaker_size',
            new_name='sizes',
        ),
    ]
