# Generated by Django 3.1.6 on 2022-09-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
